import 'package:flutter/material.dart';
import 'package:pharma6/models/pharmacies_liste_model.dart';
import 'informations_pharmacies_lome.dart';
import 'informations_pharmacies_kara.dart';
import 'informations_organismes_sante.dart';
import 'package:pharma6/models/organismes_sante_liste_model.dart';
import 'package:pharma6/models/accueil_card_model.dart';



class MesListes {

  //LOME LISTE
  static List<PharmaciesListeModels> lomeListe() {
    return [
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH1,
          InformationsPharmaciesLome.locPH1,
          InformationsPharmaciesLome.contPH1_1,
          InformationsPharmaciesLome.contPH1_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH2,
          InformationsPharmaciesLome.locPH2,
          InformationsPharmaciesLome.contPH2_1,
          InformationsPharmaciesLome.contPH2_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH3,
          InformationsPharmaciesLome.locPH3,
          InformationsPharmaciesLome.contPH3_1,
          InformationsPharmaciesLome.contPH3_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH4,
          InformationsPharmaciesLome.locPH4,
          InformationsPharmaciesLome.contPH4_1,
          InformationsPharmaciesLome.contPH4_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH5,
          InformationsPharmaciesLome.locPH5,
          InformationsPharmaciesLome.contPH5_1,
          InformationsPharmaciesLome.contPH5_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH6,
          InformationsPharmaciesLome.locPH6,
          InformationsPharmaciesLome.contPH6_1,
          InformationsPharmaciesLome.contPH6_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH7,
          InformationsPharmaciesLome.locPH7,
          InformationsPharmaciesLome.contPH7_1,
          InformationsPharmaciesLome.contPH7_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH8,
          InformationsPharmaciesLome.locPH8,
          InformationsPharmaciesLome.contPH8_1,
          InformationsPharmaciesLome.contPH8_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH9,
          InformationsPharmaciesLome.locPH9,
          InformationsPharmaciesLome.contPH9_1,
          InformationsPharmaciesLome.contPH9_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH10,
          InformationsPharmaciesLome.locPH10,
          InformationsPharmaciesLome.contPH10_1,
          InformationsPharmaciesLome.contPH10_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH11,
          InformationsPharmaciesLome.locPH11,
          InformationsPharmaciesLome.contPH11_1,
          InformationsPharmaciesLome.contPH11_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH12,
          InformationsPharmaciesLome.locPH12,
          InformationsPharmaciesLome.contPH12_1,
          InformationsPharmaciesLome.contPH12_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH13,
          InformationsPharmaciesLome.locPH13,
          InformationsPharmaciesLome.contPH13_1,
          InformationsPharmaciesLome.contPH13_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH14,
          InformationsPharmaciesLome.locPH14,
          InformationsPharmaciesLome.contPH14_1,
          InformationsPharmaciesLome.contPH14_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH15,
          InformationsPharmaciesLome.locPH15,
          InformationsPharmaciesLome.contPH15_1,
          InformationsPharmaciesLome.contPH15_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH16,
          InformationsPharmaciesLome.locPH16,
          InformationsPharmaciesLome.contPH16_1,
          InformationsPharmaciesLome.contPH16_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH17,
          InformationsPharmaciesLome.locPH17,
          InformationsPharmaciesLome.contPH17_1,
          InformationsPharmaciesLome.contPH17_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH18,
          InformationsPharmaciesLome.locPH18,
          InformationsPharmaciesLome.contPH18_1,
          InformationsPharmaciesLome.contPH18_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH19,
          InformationsPharmaciesLome.locPH19,
          InformationsPharmaciesLome.contPH19_1,
          InformationsPharmaciesLome.contPH19_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH20,
          InformationsPharmaciesLome.locPH20,
          InformationsPharmaciesLome.contPH20_1,
          InformationsPharmaciesLome.contPH20_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH21,
          InformationsPharmaciesLome.locPH21,
          InformationsPharmaciesLome.contPH21_1,
          InformationsPharmaciesLome.contPH21_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH22,
          InformationsPharmaciesLome.locPH22,
          InformationsPharmaciesLome.contPH22_1,
          InformationsPharmaciesLome.contPH22_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH23,
          InformationsPharmaciesLome.locPH23,
          InformationsPharmaciesLome.contPH23_1,
          InformationsPharmaciesLome.contPH23_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH24,
          InformationsPharmaciesLome.locPH24,
          InformationsPharmaciesLome.contPH24_1,
          InformationsPharmaciesLome.contPH24_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH25,
          InformationsPharmaciesLome.locPH25,
          InformationsPharmaciesLome.contPH25_1,
          InformationsPharmaciesLome.contPH25_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH26,
          InformationsPharmaciesLome.locPH26,
          InformationsPharmaciesLome.contPH26_1,
          InformationsPharmaciesLome.contPH26_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH27,
          InformationsPharmaciesLome.locPH27,
          InformationsPharmaciesLome.contPH27_1,
          InformationsPharmaciesLome.contPH27_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH28,
          InformationsPharmaciesLome.locPH28,
          InformationsPharmaciesLome.contPH28_1,
          InformationsPharmaciesLome.contPH28_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH29,
          InformationsPharmaciesLome.locPH29,
          InformationsPharmaciesLome.contPH29_1,
          InformationsPharmaciesLome.contPH29_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH30,
          InformationsPharmaciesLome.locPH30,
          InformationsPharmaciesLome.contPH30_1,
          InformationsPharmaciesLome.contPH30_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH31,
          InformationsPharmaciesLome.locPH31,
          InformationsPharmaciesLome.contPH31_1,
          InformationsPharmaciesLome.contPH31_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH32,
          InformationsPharmaciesLome.locPH32,
          InformationsPharmaciesLome.contPH32_1,
          InformationsPharmaciesLome.contPH32_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH33,
          InformationsPharmaciesLome.locPH33,
          InformationsPharmaciesLome.contPH33_1,
          InformationsPharmaciesLome.contPH33_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH34,
          InformationsPharmaciesLome.locPH34,
          InformationsPharmaciesLome.contPH34_1,
          InformationsPharmaciesLome.contPH34_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH35,
          InformationsPharmaciesLome.locPH35,
          InformationsPharmaciesLome.contPH35_1,
          InformationsPharmaciesLome.contPH35_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH36,
          InformationsPharmaciesLome.locPH36,
          InformationsPharmaciesLome.contPH36_1,
          InformationsPharmaciesLome.contPH36_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH37,
          InformationsPharmaciesLome.locPH37,
          InformationsPharmaciesLome.contPH37_1,
          InformationsPharmaciesLome.contPH37_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH38,
          InformationsPharmaciesLome.locPH38,
          InformationsPharmaciesLome.contPH38_1,
          InformationsPharmaciesLome.contPH38_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH39,
          InformationsPharmaciesLome.locPH39,
          InformationsPharmaciesLome.contPH39_1,
          InformationsPharmaciesLome.contPH39_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH40,
          InformationsPharmaciesLome.locPH40,
          InformationsPharmaciesLome.contPH40_1,
          InformationsPharmaciesLome.contPH40_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH41,
          InformationsPharmaciesLome.locPH41,
          InformationsPharmaciesLome.contPH41_1,
          InformationsPharmaciesLome.contPH41_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH42,
          InformationsPharmaciesLome.locPH42,
          InformationsPharmaciesLome.contPH42_1,
          InformationsPharmaciesLome.contPH42_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH43,
          InformationsPharmaciesLome.locPH43,
          InformationsPharmaciesLome.contPH43_1,
          InformationsPharmaciesLome.contPH43_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH44,
          InformationsPharmaciesLome.locPH44,
          InformationsPharmaciesLome.contPH44_1,
          InformationsPharmaciesLome.contPH44_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH45,
          InformationsPharmaciesLome.locPH45,
          InformationsPharmaciesLome.contPH45_1,
          InformationsPharmaciesLome.contPH45_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH46,
          InformationsPharmaciesLome.locPH46,
          InformationsPharmaciesLome.contPH46_1,
          InformationsPharmaciesLome.contPH46_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH47,
          InformationsPharmaciesLome.locPH47,
          InformationsPharmaciesLome.contPH47_1,
          InformationsPharmaciesLome.contPH47_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH48,
          InformationsPharmaciesLome.locPH48,
          InformationsPharmaciesLome.contPH48_1,
          InformationsPharmaciesLome.contPH48_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH49,
          InformationsPharmaciesLome.locPH49,
          InformationsPharmaciesLome.contPH49_1,
          InformationsPharmaciesLome.contPH49_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH50,
          InformationsPharmaciesLome.locPH50,
          InformationsPharmaciesLome.contPH50_1,
          InformationsPharmaciesLome.contPH50_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH51,
          InformationsPharmaciesLome.locPH51,
          InformationsPharmaciesLome.contPH51_1,
          InformationsPharmaciesLome.contPH51_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH52,
          InformationsPharmaciesLome.locPH52,
          InformationsPharmaciesLome.contPH52_1,
          InformationsPharmaciesLome.contPH52_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH53,
          InformationsPharmaciesLome.locPH53,
          InformationsPharmaciesLome.contPH53_1,
          InformationsPharmaciesLome.contPH53_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH54,
          InformationsPharmaciesLome.locPH54,
          InformationsPharmaciesLome.contPH54_1,
          InformationsPharmaciesLome.contPH54_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH55,
          InformationsPharmaciesLome.locPH55,
          InformationsPharmaciesLome.contPH55_1,
          InformationsPharmaciesLome.contPH55_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH56,
          InformationsPharmaciesLome.locPH56,
          InformationsPharmaciesLome.contPH56_1,
          InformationsPharmaciesLome.contPH56_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH57,
          InformationsPharmaciesLome.locPH57,
          InformationsPharmaciesLome.contPH57_1,
          InformationsPharmaciesLome.contPH57_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH58,
          InformationsPharmaciesLome.locPH58,
          InformationsPharmaciesLome.contPH58_1,
          InformationsPharmaciesLome.contPH58_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH59,
          InformationsPharmaciesLome.locPH59,
          InformationsPharmaciesLome.contPH59_1,
          InformationsPharmaciesLome.contPH59_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH60,
          InformationsPharmaciesLome.locPH60,
          InformationsPharmaciesLome.contPH60_1,
          InformationsPharmaciesLome.contPH60_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH61,
          InformationsPharmaciesLome.locPH61,
          InformationsPharmaciesLome.contPH61_1,
          InformationsPharmaciesLome.contPH61_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH62,
          InformationsPharmaciesLome.locPH62,
          InformationsPharmaciesLome.contPH62_1,
          InformationsPharmaciesLome.contPH62_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH63,
          InformationsPharmaciesLome.locPH63,
          InformationsPharmaciesLome.contPH63_1,
          InformationsPharmaciesLome.contPH63_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH64,
          InformationsPharmaciesLome.locPH64,
          InformationsPharmaciesLome.contPH64_1,
          InformationsPharmaciesLome.contPH64_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH65,
          InformationsPharmaciesLome.locPH65,
          InformationsPharmaciesLome.contPH65_1,
          InformationsPharmaciesLome.contPH65_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH66,
          InformationsPharmaciesLome.locPH66,
          InformationsPharmaciesLome.contPH66_1,
          InformationsPharmaciesLome.contPH66_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH67,
          InformationsPharmaciesLome.locPH67,
          InformationsPharmaciesLome.contPH67_1,
          InformationsPharmaciesLome.contPH67_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH68,
          InformationsPharmaciesLome.locPH68,
          InformationsPharmaciesLome.contPH68_1,
          InformationsPharmaciesLome.contPH68_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH69,
          InformationsPharmaciesLome.locPH69,
          InformationsPharmaciesLome.contPH69_1,
          InformationsPharmaciesLome.contPH69_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH70,
          InformationsPharmaciesLome.locPH70,
          InformationsPharmaciesLome.contPH70_1,
          InformationsPharmaciesLome.contPH70_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH71,
          InformationsPharmaciesLome.locPH71,
          InformationsPharmaciesLome.contPH71_1,
          InformationsPharmaciesLome.contPH71_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH72,
          InformationsPharmaciesLome.locPH72,
          InformationsPharmaciesLome.contPH72_1,
          InformationsPharmaciesLome.contPH72_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH73,
          InformationsPharmaciesLome.locPH73,
          InformationsPharmaciesLome.contPH73_1,
          InformationsPharmaciesLome.contPH73_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH74,
          InformationsPharmaciesLome.locPH74,
          InformationsPharmaciesLome.contPH74_1,
          InformationsPharmaciesLome.contPH74_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH75,
          InformationsPharmaciesLome.locPH75,
          InformationsPharmaciesLome.contPH75_1,
          InformationsPharmaciesLome.contPH75_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH76,
          InformationsPharmaciesLome.locPH76,
          InformationsPharmaciesLome.contPH76_1,
          InformationsPharmaciesLome.contPH76_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH77,
          InformationsPharmaciesLome.locPH77,
          InformationsPharmaciesLome.contPH77_1,
          InformationsPharmaciesLome.contPH77_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH78,
          InformationsPharmaciesLome.locPH78,
          InformationsPharmaciesLome.contPH78_1,
          InformationsPharmaciesLome.contPH78_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH79,
          InformationsPharmaciesLome.locPH79,
          InformationsPharmaciesLome.contPH79_1,
          InformationsPharmaciesLome.contPH79_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH80,
          InformationsPharmaciesLome.locPH80,
          InformationsPharmaciesLome.contPH80_1,
          InformationsPharmaciesLome.contPH80_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH81,
          InformationsPharmaciesLome.locPH81,
          InformationsPharmaciesLome.contPH81_1,
          InformationsPharmaciesLome.contPH81_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH82,
          InformationsPharmaciesLome.locPH82,
          InformationsPharmaciesLome.contPH82_1,
          InformationsPharmaciesLome.contPH82_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH83,
          InformationsPharmaciesLome.locPH83,
          InformationsPharmaciesLome.contPH83_1,
          InformationsPharmaciesLome.contPH83_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH84,
          InformationsPharmaciesLome.locPH84,
          InformationsPharmaciesLome.contPH84_1,
          InformationsPharmaciesLome.contPH84_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH85,
          InformationsPharmaciesLome.locPH85,
          InformationsPharmaciesLome.contPH85_1,
          InformationsPharmaciesLome.contPH85_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH86,
          InformationsPharmaciesLome.locPH86,
          InformationsPharmaciesLome.contPH86_1,
          InformationsPharmaciesLome.contPH86_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH87,
          InformationsPharmaciesLome.locPH87,
          InformationsPharmaciesLome.contPH87_1,
          InformationsPharmaciesLome.contPH87_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH88,
          InformationsPharmaciesLome.locPH88,
          InformationsPharmaciesLome.contPH88_1,
          InformationsPharmaciesLome.contPH88_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH89,
          InformationsPharmaciesLome.locPH89,
          InformationsPharmaciesLome.contPH89_1,
          InformationsPharmaciesLome.contPH89_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH90,
          InformationsPharmaciesLome.locPH90,
          InformationsPharmaciesLome.contPH90_1,
          InformationsPharmaciesLome.contPH90_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH91,
          InformationsPharmaciesLome.locPH91,
          InformationsPharmaciesLome.contPH91_1,
          InformationsPharmaciesLome.contPH91_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH92,
          InformationsPharmaciesLome.locPH92,
          InformationsPharmaciesLome.contPH92_1,
          InformationsPharmaciesLome.contPH92_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH93,
          InformationsPharmaciesLome.locPH93,
          InformationsPharmaciesLome.contPH93_1,
          InformationsPharmaciesLome.contPH93_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH94,
          InformationsPharmaciesLome.locPH94,
          InformationsPharmaciesLome.contPH94_1,
          InformationsPharmaciesLome.contPH94_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH95,
          InformationsPharmaciesLome.locPH95,
          InformationsPharmaciesLome.contPH95_1,
          InformationsPharmaciesLome.contPH95_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH96,
          InformationsPharmaciesLome.locPH96,
          InformationsPharmaciesLome.contPH96_1,
          InformationsPharmaciesLome.contPH96_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH97,
          InformationsPharmaciesLome.locPH97,
          InformationsPharmaciesLome.contPH97_1,
          InformationsPharmaciesLome.contPH97_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH98,
          InformationsPharmaciesLome.locPH98,
          InformationsPharmaciesLome.contPH98_1,
          InformationsPharmaciesLome.contPH98_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH99,
          InformationsPharmaciesLome.locPH99,
          InformationsPharmaciesLome.contPH99_1,
          InformationsPharmaciesLome.contPH99_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH100,
          InformationsPharmaciesLome.locPH100,
          InformationsPharmaciesLome.contPH100_1,
          InformationsPharmaciesLome.contPH100_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH101,
          InformationsPharmaciesLome.locPH101,
          InformationsPharmaciesLome.contPH101_1,
          InformationsPharmaciesLome.contPH101_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH102,
          InformationsPharmaciesLome.locPH102,
          InformationsPharmaciesLome.contPH102_1,
          InformationsPharmaciesLome.contPH102_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH103,
          InformationsPharmaciesLome.locPH103,
          InformationsPharmaciesLome.contPH103_1,
          InformationsPharmaciesLome.contPH103_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH104,
          InformationsPharmaciesLome.locPH104,
          InformationsPharmaciesLome.contPH104_1,
          InformationsPharmaciesLome.contPH104_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH105,
          InformationsPharmaciesLome.locPH105,
          InformationsPharmaciesLome.contPH105_1,
          InformationsPharmaciesLome.contPH105_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH106,
          InformationsPharmaciesLome.locPH106,
          InformationsPharmaciesLome.contPH106_1,
          InformationsPharmaciesLome.contPH106_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH107,
          InformationsPharmaciesLome.locPH107,
          InformationsPharmaciesLome.contPH107_1,
          InformationsPharmaciesLome.contPH107_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH108,
          InformationsPharmaciesLome.locPH108,
          InformationsPharmaciesLome.contPH108_1,
          InformationsPharmaciesLome.contPH108_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH109,
          InformationsPharmaciesLome.locPH109,
          InformationsPharmaciesLome.contPH109_1,
          InformationsPharmaciesLome.contPH109_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH110,
          InformationsPharmaciesLome.locPH110,
          InformationsPharmaciesLome.contPH110_1,
          InformationsPharmaciesLome.contPH110_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH111,
          InformationsPharmaciesLome.locPH111,
          InformationsPharmaciesLome.contPH111_1,
          InformationsPharmaciesLome.contPH111_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH112,
          InformationsPharmaciesLome.locPH112,
          InformationsPharmaciesLome.contPH112_1,
          InformationsPharmaciesLome.contPH112_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH113,
          InformationsPharmaciesLome.locPH113,
          InformationsPharmaciesLome.contPH113_1,
          InformationsPharmaciesLome.contPH113_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH114,
          InformationsPharmaciesLome.locPH114,
          InformationsPharmaciesLome.contPH114_1,
          InformationsPharmaciesLome.contPH114_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH115,
          InformationsPharmaciesLome.locPH115,
          InformationsPharmaciesLome.contPH115_1,
          InformationsPharmaciesLome.contPH115_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH116,
          InformationsPharmaciesLome.locPH116,
          InformationsPharmaciesLome.contPH116_1,
          InformationsPharmaciesLome.contPH116_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH117,
          InformationsPharmaciesLome.locPH117,
          InformationsPharmaciesLome.contPH117_1,
          InformationsPharmaciesLome.contPH117_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH118,
          InformationsPharmaciesLome.locPH118,
          InformationsPharmaciesLome.contPH118_1,
          InformationsPharmaciesLome.contPH118_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH119,
          InformationsPharmaciesLome.locPH119,
          InformationsPharmaciesLome.contPH119_1,
          InformationsPharmaciesLome.contPH119_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH120,
          InformationsPharmaciesLome.locPH120,
          InformationsPharmaciesLome.contPH120_1,
          InformationsPharmaciesLome.contPH120_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH121,
          InformationsPharmaciesLome.locPH121,
          InformationsPharmaciesLome.contPH121_1,
          InformationsPharmaciesLome.contPH121_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH122,
          InformationsPharmaciesLome.locPH122,
          InformationsPharmaciesLome.contPH122_1,
          InformationsPharmaciesLome.contPH122_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH123,
          InformationsPharmaciesLome.locPH123,
          InformationsPharmaciesLome.contPH123_1,
          InformationsPharmaciesLome.contPH123_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH124,
          InformationsPharmaciesLome.locPH124,
          InformationsPharmaciesLome.contPH124_1,
          InformationsPharmaciesLome.contPH124_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH125,
          InformationsPharmaciesLome.locPH125,
          InformationsPharmaciesLome.contPH125_1,
          InformationsPharmaciesLome.contPH125_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH126,
          InformationsPharmaciesLome.locPH126,
          InformationsPharmaciesLome.contPH126_1,
          InformationsPharmaciesLome.contPH126_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH127,
          InformationsPharmaciesLome.locPH127,
          InformationsPharmaciesLome.contPH127_1,
          InformationsPharmaciesLome.contPH127_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH128,
          InformationsPharmaciesLome.locPH128,
          InformationsPharmaciesLome.contPH128_1,
          InformationsPharmaciesLome.contPH128_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH129,
          InformationsPharmaciesLome.locPH129,
          InformationsPharmaciesLome.contPH129_1,
          InformationsPharmaciesLome.contPH129_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH130,
          InformationsPharmaciesLome.locPH130,
          InformationsPharmaciesLome.contPH130_1,
          InformationsPharmaciesLome.contPH130_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH131,
          InformationsPharmaciesLome.locPH131,
          InformationsPharmaciesLome.contPH131_1,
          InformationsPharmaciesLome.contPH131_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH132,
          InformationsPharmaciesLome.locPH132,
          InformationsPharmaciesLome.contPH132_1,
          InformationsPharmaciesLome.contPH132_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH133,
          InformationsPharmaciesLome.locPH133,
          InformationsPharmaciesLome.contPH133_1,
          InformationsPharmaciesLome.contPH133_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH134,
          InformationsPharmaciesLome.locPH134,
          InformationsPharmaciesLome.contPH134_1,
          InformationsPharmaciesLome.contPH134_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH135,
          InformationsPharmaciesLome.locPH135,
          InformationsPharmaciesLome.contPH135_1,
          InformationsPharmaciesLome.contPH135_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH136,
          InformationsPharmaciesLome.locPH136,
          InformationsPharmaciesLome.contPH136_1,
          InformationsPharmaciesLome.contPH136_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH137,
          InformationsPharmaciesLome.locPH137,
          InformationsPharmaciesLome.contPH137_1,
          InformationsPharmaciesLome.contPH137_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH138,
          InformationsPharmaciesLome.locPH138,
          InformationsPharmaciesLome.contPH138_1,
          InformationsPharmaciesLome.contPH138_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH139,
          InformationsPharmaciesLome.locPH139,
          InformationsPharmaciesLome.contPH139_1,
          InformationsPharmaciesLome.contPH139_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH140,
          InformationsPharmaciesLome.locPH140,
          InformationsPharmaciesLome.contPH140_1,
          InformationsPharmaciesLome.contPH140_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH141,
          InformationsPharmaciesLome.locPH141,
          InformationsPharmaciesLome.contPH141_1,
          InformationsPharmaciesLome.contPH141_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH142,
          InformationsPharmaciesLome.locPH142,
          InformationsPharmaciesLome.contPH142_1,
          InformationsPharmaciesLome.contPH142_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH143,
          InformationsPharmaciesLome.locPH143,
          InformationsPharmaciesLome.contPH143_1,
          InformationsPharmaciesLome.contPH143_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH144,
          InformationsPharmaciesLome.locPH144,
          InformationsPharmaciesLome.contPH144_1,
          InformationsPharmaciesLome.contPH144_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH145,
          InformationsPharmaciesLome.locPH145,
          InformationsPharmaciesLome.contPH145_1,
          InformationsPharmaciesLome.contPH145_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH146,
          InformationsPharmaciesLome.locPH146,
          InformationsPharmaciesLome.contPH146_1,
          InformationsPharmaciesLome.contPH146_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH147,
          InformationsPharmaciesLome.locPH147,
          InformationsPharmaciesLome.contPH147_1,
          InformationsPharmaciesLome.contPH147_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH148,
          InformationsPharmaciesLome.locPH148,
          InformationsPharmaciesLome.contPH148_1,
          InformationsPharmaciesLome.contPH148_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH149,
          InformationsPharmaciesLome.locPH149,
          InformationsPharmaciesLome.contPH149_1,
          InformationsPharmaciesLome.contPH149_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH150,
          InformationsPharmaciesLome.locPH150,
          InformationsPharmaciesLome.contPH150_1,
          InformationsPharmaciesLome.contPH150_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH151,
          InformationsPharmaciesLome.locPH151,
          InformationsPharmaciesLome.contPH151_1,
          InformationsPharmaciesLome.contPH151_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH152,
          InformationsPharmaciesLome.locPH152,
          InformationsPharmaciesLome.contPH152_1,
          InformationsPharmaciesLome.contPH152_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH153,
          InformationsPharmaciesLome.locPH153,
          InformationsPharmaciesLome.contPH153_1,
          InformationsPharmaciesLome.contPH153_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH154,
          InformationsPharmaciesLome.locPH154,
          InformationsPharmaciesLome.contPH154_1,
          InformationsPharmaciesLome.contPH154_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH155,
          InformationsPharmaciesLome.locPH155,
          InformationsPharmaciesLome.contPH155_1,
          InformationsPharmaciesLome.contPH155_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH156,
          InformationsPharmaciesLome.locPH156,
          InformationsPharmaciesLome.contPH156_1,
          InformationsPharmaciesLome.contPH156_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH157,
          InformationsPharmaciesLome.locPH157,
          InformationsPharmaciesLome.contPH157_1,
          InformationsPharmaciesLome.contPH157_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH158,
          InformationsPharmaciesLome.locPH158,
          InformationsPharmaciesLome.contPH158_1,
          InformationsPharmaciesLome.contPH158_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH159,
          InformationsPharmaciesLome.locPH159,
          InformationsPharmaciesLome.contPH159_1,
          InformationsPharmaciesLome.contPH159_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH160,
          InformationsPharmaciesLome.locPH160,
          InformationsPharmaciesLome.contPH160_1,
          InformationsPharmaciesLome.contPH160_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH161,
          InformationsPharmaciesLome.locPH161,
          InformationsPharmaciesLome.contPH161_1,
          InformationsPharmaciesLome.contPH161_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH162,
          InformationsPharmaciesLome.locPH162,
          InformationsPharmaciesLome.contPH162_1,
          InformationsPharmaciesLome.contPH162_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH163,
          InformationsPharmaciesLome.locPH163,
          InformationsPharmaciesLome.contPH163_1,
          InformationsPharmaciesLome.contPH163_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH164,
          InformationsPharmaciesLome.locPH164,
          InformationsPharmaciesLome.contPH164_1,
          InformationsPharmaciesLome.contPH164_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH165,
          InformationsPharmaciesLome.locPH165,
          InformationsPharmaciesLome.contPH165_1,
          InformationsPharmaciesLome.contPH165_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH166,
          InformationsPharmaciesLome.locPH166,
          InformationsPharmaciesLome.contPH166_1,
          InformationsPharmaciesLome.contPH166_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH167,
          InformationsPharmaciesLome.locPH167,
          InformationsPharmaciesLome.contPH167_1,
          InformationsPharmaciesLome.contPH167_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH168,
          InformationsPharmaciesLome.locPH168,
          InformationsPharmaciesLome.contPH168_1,
          InformationsPharmaciesLome.contPH168_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH169,
          InformationsPharmaciesLome.locPH169,
          InformationsPharmaciesLome.contPH169_1,
          InformationsPharmaciesLome.contPH169_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH170,
          InformationsPharmaciesLome.locPH170,
          InformationsPharmaciesLome.contPH170_1,
          InformationsPharmaciesLome.contPH170_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH171,
          InformationsPharmaciesLome.locPH171,
          InformationsPharmaciesLome.contPH171_1,
          InformationsPharmaciesLome.contPH171_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH172,
          InformationsPharmaciesLome.locPH172,
          InformationsPharmaciesLome.contPH172_1,
          InformationsPharmaciesLome.contPH172_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH173,
          InformationsPharmaciesLome.locPH173,
          InformationsPharmaciesLome.contPH173_1,
          InformationsPharmaciesLome.contPH173_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH174,
          InformationsPharmaciesLome.locPH174,
          InformationsPharmaciesLome.contPH174_1,
          InformationsPharmaciesLome.contPH174_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH175,
          InformationsPharmaciesLome.locPH175,
          InformationsPharmaciesLome.contPH175_1,
          InformationsPharmaciesLome.contPH175_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH176,
          InformationsPharmaciesLome.locPH176,
          InformationsPharmaciesLome.contPH176_1,
          InformationsPharmaciesLome.contPH176_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH177,
          InformationsPharmaciesLome.locPH177,
          InformationsPharmaciesLome.contPH177_1,
          InformationsPharmaciesLome.contPH177_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH178,
          InformationsPharmaciesLome.locPH178,
          InformationsPharmaciesLome.contPH178_1,
          InformationsPharmaciesLome.contPH178_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH179,
          InformationsPharmaciesLome.locPH179,
          InformationsPharmaciesLome.contPH179_1,
          InformationsPharmaciesLome.contPH179_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH180,
          InformationsPharmaciesLome.locPH180,
          InformationsPharmaciesLome.contPH180_1,
          InformationsPharmaciesLome.contPH180_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH181,
          InformationsPharmaciesLome.locPH181,
          InformationsPharmaciesLome.contPH181_1,
          InformationsPharmaciesLome.contPH181_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH182,
          InformationsPharmaciesLome.locPH182,
          InformationsPharmaciesLome.contPH182_1,
          InformationsPharmaciesLome.contPH182_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH183,
          InformationsPharmaciesLome.locPH183,
          InformationsPharmaciesLome.contPH183_1,
          InformationsPharmaciesLome.contPH183_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH184,
          InformationsPharmaciesLome.locPH184,
          InformationsPharmaciesLome.contPH184_1,
          InformationsPharmaciesLome.contPH184_2),
      PharmaciesListeModels(
          InformationsPharmaciesLome.nomPH185,
          InformationsPharmaciesLome.locPH185,
          InformationsPharmaciesLome.contPH185_1,
          InformationsPharmaciesLome.contPH185_2),
    ];
  }

  //KARA LISTE
  static List<PharmaciesListeModels> karaListe() {
    return [
      PharmaciesListeModels(
          InformationsPharmaciesKara.nomPHK1,
          InformationsPharmaciesKara.locPHK1,
          InformationsPharmaciesKara.contPHK1_1,
          InformationsPharmaciesKara.contPHK1_2),
      PharmaciesListeModels(
          InformationsPharmaciesKara.nomPHK2,
          InformationsPharmaciesKara.locPHK2,
          InformationsPharmaciesKara.contPHK2_1,
          InformationsPharmaciesKara.contPHK2_2),
      PharmaciesListeModels(
          InformationsPharmaciesKara.nomPHK3,
          InformationsPharmaciesKara.locPHK3,
          InformationsPharmaciesKara.contPHK3_1,
          InformationsPharmaciesKara.contPHK3_2),
      PharmaciesListeModels(
          InformationsPharmaciesKara.nomPHK4,
          InformationsPharmaciesKara.locPHK4,
          InformationsPharmaciesKara.contPHK4_1,
          InformationsPharmaciesKara.contPHK4_2),
      PharmaciesListeModels(
          InformationsPharmaciesKara.nomPHK5,
          InformationsPharmaciesKara.locPHK5,
          InformationsPharmaciesKara.contPHK5_1,
          InformationsPharmaciesKara.contPHK5_2),
      PharmaciesListeModels(
          InformationsPharmaciesKara.nomPHK6,
          InformationsPharmaciesKara.locPHK6,
          InformationsPharmaciesKara.contPHK6_1,
          InformationsPharmaciesKara.contPHK6_2),
      PharmaciesListeModels(
          InformationsPharmaciesKara.nomPHK7,
          InformationsPharmaciesKara.locPHK7,
          InformationsPharmaciesKara.contPHK7_1,
          InformationsPharmaciesKara.contPHK7_2),
    ];
  }

  //ACCUEIL CARD LISTE
  static List<AccueilCardModel> accueilCardListe()
  {
    return [
      AccueilCardModel(1, "Pharmacies\nde Garde", Icons.account_balance),
      AccueilCardModel(2, "Annuaire de\nPharmacies", Icons.add_business),
      AccueilCardModel(3, "Organismes\nde Santé", Icons.add_business),
      AccueilCardModel(4, "Bon à\nSavoir", Icons.account_balance),
      AccueilCardModel(5, "Donnez\nVotre Avis", Icons.person),
      AccueilCardModel(6, "Info sur \nl'Application", Icons.add_card_sharp),
    ];
  }

  //LISTE ORGANISMES DE SANTE
  static List<OrganismesSanteListeItem> organismesSanteListe()
  {
    return[
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution1, InformationsOrganismesSante.locInstitution1, InformationsOrganismesSante.contInstitution1),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution2, InformationsOrganismesSante.locInstitution2, InformationsOrganismesSante.contInstitution2),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution3, InformationsOrganismesSante.locInstitution3, InformationsOrganismesSante.contInstitution3),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution4, InformationsOrganismesSante.locInstitution4, InformationsOrganismesSante.contInstitution4),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution5, InformationsOrganismesSante.locInstitution5, InformationsOrganismesSante.contInstitution5),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution6, InformationsOrganismesSante.locInstitution6, InformationsOrganismesSante.contInstitution6),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution7, InformationsOrganismesSante.locInstitution7, InformationsOrganismesSante.contInstitution7),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution8, InformationsOrganismesSante.locInstitution8, InformationsOrganismesSante.contInstitution8),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution9, InformationsOrganismesSante.locInstitution9, InformationsOrganismesSante.contInstitution9),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution10, InformationsOrganismesSante.locInstitution10, InformationsOrganismesSante.contInstitution10),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution11, InformationsOrganismesSante.locInstitution11, InformationsOrganismesSante.contInstitution11),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution12, InformationsOrganismesSante.locInstitution12, InformationsOrganismesSante.contInstitution12),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution13, InformationsOrganismesSante.locInstitution13, InformationsOrganismesSante.contInstitution13),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution14, InformationsOrganismesSante.locInstitution14, InformationsOrganismesSante.contInstitution14),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution15, InformationsOrganismesSante.locInstitution15, InformationsOrganismesSante.contInstitution15),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution16, InformationsOrganismesSante.locInstitution16, InformationsOrganismesSante.contInstitution16),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution17, InformationsOrganismesSante.locInstitution17, InformationsOrganismesSante.contInstitution17),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution18, InformationsOrganismesSante.locInstitution18, InformationsOrganismesSante.contInstitution18),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution19, InformationsOrganismesSante.locInstitution19, InformationsOrganismesSante.contInstitution19),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution20, InformationsOrganismesSante.locInstitution20, InformationsOrganismesSante.contInstitution20),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution21, InformationsOrganismesSante.locInstitution21, InformationsOrganismesSante.contInstitution21),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution22, InformationsOrganismesSante.locInstitution22, InformationsOrganismesSante.contInstitution22),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution23, InformationsOrganismesSante.locInstitution23, InformationsOrganismesSante.contInstitution23),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution24, InformationsOrganismesSante.locInstitution24, InformationsOrganismesSante.contInstitution24),
   OrganismesSanteListeItem(Icons.account_balance, InformationsOrganismesSante.nomInstitution25, InformationsOrganismesSante.locInstitution25, InformationsOrganismesSante.contInstitution25)

    ];
  }
}

